import os

files = {
    "backend/requirements.txt": """fastapi==0.103.1\nuvicorn==0.23.2\nsqlalchemy==2.0.20\npsycopg2-binary==2.9.7\npydantic==2.3.0\npydantic-settings==2.0.3\npasslib[bcrypt]==1.7.4\npython-jose[cryptography]==3.3.0\npython-multipart==0.0.6\nopenai==1.3.5\nzhipuai==2.0.1\n""",
    "backend/app/core/config.py": """from pydantic_settings import BaseSettings\nimport os\nclass Settings(BaseSettings):\n    PROJECT_NAME: str = "AIGC Edu Agent API"\n    API_V1_STR: str = "/api/v1"\n    POSTGRES_SERVER: str = os.getenv("POSTGRES_SERVER", "localhost")\n    POSTGRES_USER: str = os.getenv("POSTGRES_USER", "postgres")\n    POSTGRES_PASSWORD: str = os.getenv("POSTGRES_PASSWORD", "postgres")\n    POSTGRES_DB: str = os.getenv("POSTGRES_DB", "aigc_db")\n    SQLALCHEMY_DATABASE_URI: str = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_SERVER}/{POSTGRES_DB}"\n    SECRET_KEY: str = os.getenv("SECRET_KEY", "dev_secret_key_change_me")\n    ALGORITHM: str = "HS256"\n    ACCESS_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 7\n    OPENAI_API_KEY: str = os.getenv("OPENAI_API_KEY", "")\n    CHATGLM_API_KEY: str = os.getenv("CHATGLM_API_KEY", "")\n    ACTIVE_MODEL: str = os.getenv("ACTIVE_MODEL", "gpt-4")\nsettings = Settings()\n""",
    "backend/app/core/security.py": """from datetime import datetime, timedelta\nfrom typing import Optional\nfrom jose import jwt\nfrom passlib.context import CryptContext\nfrom app.core.config import settings\npwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")\ndef verify_password(plain_password: str, hashed_password: str) -> bool:\n    return pwd_context.verify(plain_password, hashed_password)\ndef get_password_hash(password: str) -> str:\n    return pwd_context.hash(password)\ndef create_access_token(subject: str | int, expires_delta: Optional[timedelta] = None) -> str:\n    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES))\n    return jwt.encode({"exp": expire, "sub": str(subject)}, settings.SECRET_KEY, algorithm=settings.ALGORITHM)\n""",
    "backend/app/db/session.py": """from sqlalchemy import create_engine\nfrom sqlalchemy.orm import sessionmaker\nfrom app.core.config import settings\nengine = create_engine(settings.SQLALCHEMY_DATABASE_URI, pool_pre_ping=True)\nSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()\n""",
    "backend/app/db/models.py": """from sqlalchemy import Column, Integer, String, Boolean, Text\nfrom sqlalchemy.orm import declarative_base\nBase = declarative_base()\nclass User(Base):\n    __tablename__ = "users"\n    id = Column(Integer, primary_key=True, index=True)\n    email = Column(String, unique=True, index=True, nullable=False)\n    hashed_password = Column(String, nullable=False)\n    is_active = Column(Boolean, default=True)\nclass Document(Base):\n    __tablename__ = "documents"\n    id = Column(Integer, primary_key=True, index=True)\n    title = Column(String, index=True)\n    content = Column(Text)\n    owner_id = Column(Integer)\n""",
    "backend/app/schemas/user.py": """from pydantic import BaseModel, EmailStr\nclass UserCreate(BaseModel):\n    email: EmailStr\n    password: str\nclass UserResponse(BaseModel):\n    id: int\n    email: EmailStr\n    is_active: bool\n    class Config:\n        from_attributes = True\nclass Token(BaseModel):\n    access_token: str\n    token_type: str\n""",
    "backend/app/services/ai.py": """from app.core.config import settings\nimport openai\nfrom zhipuai import ZhipuAI\nopenai.api_key = settings.OPENAI_API_KEY\nzhipu_client = ZhipuAI(api_key=settings.CHATGLM_API_KEY) if settings.CHATGLM_API_KEY else None\ndef get_ai_response(prompt: str) -> str:\n    if settings.ACTIVE_MODEL == "chatglm3-6b" and zhipu_client:\n        return zhipu_client.chat.completions.create(model="chatglm3-6b", messages=[{"role": "user", "content": prompt}]).choices[0].message.content\n    return openai.chat.completions.create(model="gpt-4", messages=[{"role": "user", "content": prompt}]).choices[0].message.content\n""",
    "backend/app/api/endpoints.py": """from fastapi import APIRouter, Depends, HTTPException, status\nfrom sqlalchemy.orm import Session\nfrom fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm\nfrom app.db.session import get_db\nfrom app.db.models import User, Document\nfrom app.schemas.user import UserCreate, UserResponse, Token\nfrom app.core.security import get_password_hash, verify_password, create_access_token\nfrom app.services.ai import get_ai_response\nrouter = APIRouter()\noauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/v1/login")\n@router.post("/register", response_model=UserResponse)\ndef register(user: UserCreate, db: Session = Depends(get_db)):\n    if db.query(User).filter(User.email == user.email).first():\n        raise HTTPException(status_code=400, detail="Email registered")\n    new_user = User(email=user.email, hashed_password=get_password_hash(user.password))\n    db.add(new_user)\n    db.commit()\n    db.refresh(new_user)\n    return new_user\n@router.post("/login", response_model=Token)\ndef login(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):\n    user = db.query(User).filter(User.email == form_data.username).first()\n    if not user or not verify_password(form_data.password, user.hashed_password):\n        raise HTTPException(status_code=400, detail="Incorrect email or password")\n    return {"access_token": create_access_token(subject=user.id), "token_type": "bearer"}\n@router.post("/chat")\ndef chat(prompt: str, token: str = Depends(oauth2_scheme)):\n    return {"answer": get_ai_response(prompt)}\n@router.post("/documents")\ndef upload_document(title: str, content: str, db: Session = Depends(get_db), token: str = Depends(oauth2_scheme)):\n    doc = Document(title=title, content=content, owner_id=1)\n    db.add(doc)\n    db.commit()\n    return {"msg": "Uploaded"}\n@router.get("/recommendations")\ndef get_learning_path(token: str = Depends(oauth2_scheme)):\n    return {"path": ["Chapter 1: Intro", "Chapter 2: Advanced AI"]}\n""",
    "backend/app/main.py": """from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom app.api.endpoints import router as api_router\nfrom app.db.models import Base\nfrom app.db.session import engine\nBase.metadata.create_all(bind=engine)\napp = FastAPI(title="AIGC Edu Agent API", version="1.0.0")\napp.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])\napp.include_router(api_router, prefix="/api/v1")\n@app.get("/health")\ndef health_check(): return {"status": "ok"}\n""",
    "backend/Dockerfile": """FROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY . .\nCMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]\n""",
    "web/package.json": """{"name": "aigc-edu-web", "version": "1.0.0", "type": "module", "scripts": {"dev": "vite", "build": "tsc && vite build"}, "dependencies": {"react": "^18.2.0", "react-dom": "^18.2.0"}, "devDependencies": {"@types/react": "^18.2.15", "@types/react-dom": "^18.2.7", "@vitejs/plugin-react": "^4.0.3", "typescript": "^5.0.2", "vite": "^4.4.5"}}\n""",
    "web/vite.config.ts": """import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\nexport default defineConfig({ plugins: [react()] })\n""",
    "web/tsconfig.json": """{"compilerOptions": {"target": "ES2020", "lib": ["ES2020", "DOM", "DOM.Iterable"], "module": "ESNext", "skipLibCheck": true, "moduleResolution": "bundler", "allowImportingTsExtensions": true, "resolveJsonModule": true, "isolatedModules": true, "noEmit": true, "jsx": "react-jsx", "strict": true}, "include": ["src"]}\n""",
    "web/src/main.tsx": """import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App.tsx'\nReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)\n""",
    "web/src/App.tsx": """import { useState } from 'react'\nfunction App() {\n  const [chat, setChat] = useState('')\n  return (<div><h1>高校学习智能体 AIGC (MVP)</h1><textarea value={chat} onChange={e => setChat(e.target.value)}></textarea><button onClick={() => alert('Sending...')}>发送</button></div>)\n}\nexport default App\n""",
    "web/index.html": """<!doctype html><html lang="en"><head><meta charset="UTF-8" /><title>AIGC Edu</title></head><body><div id="root"></div><script type="module" src="/src/main.tsx"></script></body></html>\n""",
    "web/Dockerfile": """FROM node:18-alpine AS builder\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nRUN npm run build\nFROM nginx:alpine\nCOPY --from=builder /app/dist /usr/share/nginx/html\nEXPOSE 80\nCMD ["nginx", "-g", "daemon off;"]\n""",
    "miniprogram/app.json": """{"pages": ["pages/index/index"], "window": {"navigationBarTitleText": "AIGC学习智能体"}}\n""",
    "miniprogram/app.js": """App({ onLaunch() { console.log('App launched') } })\n""",
    "miniprogram/pages/index/index.wxml": """<view><text>高校学习智能体</text><input placeholder="输入问题" bindinput="onInput" /><button bindtap="onSend">提问</button></view>\n""",
    "miniprogram/pages/index/index.js": """Page({ data: { query: '' }, onInput(e) { this.setData({ query: e.detail.value }) }, onSend() { console.log(this.data.query) } })\n""",
    "docker-compose.yml": """version: '3.8'\nservices:\n  db:\n    image: postgres:15\n    environment:\n      POSTGRES_USER: postgres\n      POSTGRES_PASSWORD: postgrespassword\n      POSTGRES_DB: aigc_db\n    ports: ["5432:5432"]\n  backend:\n    build: ./backend\n    ports: ["8000:8000"]\n    environment:\n      - POSTGRES_SERVER=db\n      - SECRET_KEY=/run/secrets/jwt_secret\n    depends_on: [db]\n    secrets: [jwt_secret]\n  web:\n    build: ./web\n    ports: ["80:80"]\nsecrets:\n  jwt_secret:\n    file: ./secrets/jwt_secret.txt\n""",
    "secrets/jwt_secret.txt": "super_secret_key_for_production_env",
    "tests/backend/test_main.py": """from fastapi.testclient import TestClient\nfrom app.main import app\nclient = TestClient(app)\ndef test_health_check():\n    assert client.get("/health").status_code == 200\n""",
    "tests/web/package.json": """{"name": "web-tests", "scripts": {"test": "jest --coverage"}, "devDependencies": {"jest": "^29.5.0"}}\n""",
    "tests/web/App.test.js": """test('basic', () => { expect(1+1).toBe(2); });\n""",
    "docs/deployment.md": """# 部署与CI/CD文档\n- `POSTGRES_SERVER`\n- `OPENAI_API_KEY`\n- `CHATGLM_API_KEY`\n""",
    ".pre-commit-config.yaml": """repos:\n- repo: https://github.com/psf/black\n  rev: 23.3.0\n  hooks: [{id: black}]\n- repo: https://github.com/PyCQA/flake8\n  rev: 6.0.0\n  hooks: [{id: flake8}]\n"""
}

for file_path, content in files.items():
    dirname = os.path.dirname(file_path)
    if dirname:
        os.makedirs(dirname, exist_ok=True)
    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

print("Scaffolded all files.")
